# Generated by Django 2.0.6 on 2018-07-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_answer_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='language',
            field=models.CharField(choices=[('CP', 'C++'), ('GO', 'Go'), ('JV', 'Java'), ('JS', 'Javascript'), ('PY', 'Python'), ('RB', 'Ruby'), ('RS', 'Rust')], default='JS', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Non_Coding', 'Non-Coding'), ('Arrays and Strings', 'Arrays and Strings'), ('Linked Lists', 'Linked Lists'), ('Stacks and Queues', 'Stacks and Queues'), ('Trees and Graphs', 'Trees and Graphs'), ('Bit Manipulation', 'Bit Manipulation'), ('Math and Logic Puzzles', 'Math and Logic Puzzles'), ('Object Oriented Design', 'Object Oriented Design'), ('Recursion and Dynamic Programming', 'Recursion and Dynamic Programming'), ('System Design and Scalability', 'System Design and Scalability'), ('Sorting and Searching', 'Sorting and Searching'), ('Testing', 'Testing')], default='Non_Coding', max_length=100),
        ),
    ]
