# Generated by Django 2.0.6 on 2018-07-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20180723_0617'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AddField(
            model_name='answer',
            name='language',
            field=models.CharField(choices=[('PC', 'Psuedocode and/or Writing'), ('CP', 'C++'), ('GO', 'Go'), ('JV', 'Java'), ('JS', 'Javascript'), ('PY', 'Python'), ('RB', 'Ruby'), ('RS', 'Rust')], default='JS', max_length=30),
        ),
    ]
