# Generated by Django 2.0.6 on 2018-07-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_auto_20180723_0639'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Problem',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='question',
            new_name='problem',
        ),
    ]
