# Generated by Django 2.0.6 on 2018-07-28 19:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_auto_20180728_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 28, 19, 4, 52, 720079, tzinfo=utc)),
        ),
    ]
