# Generated by Django 2.0.6 on 2018-07-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_auto_20180729_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='language',
            field=models.CharField(choices=[('Psuedocode and/or Writing', 'Psuedocode and/or Writing'), ('C++', 'C++'), ('Go', 'Go'), ('Java', 'Java'), ('Javascript', 'Javascript'), ('Python', 'Python'), ('Ruby', 'Ruby'), ('Rust', 'Rust')], default='Javascript', max_length=30),
        ),
    ]
