# Generated by Django 2.1 on 2018-08-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0011_auto_20180814_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='language',
            field=models.CharField(choices=[('Psuedocode', 'Psuedocode and/or Writing'), ('C++', 'C++'), ('Go', 'Go'), ('Java', 'Java'), ('Javascript', 'Javascript'), ('Python', 'Python'), ('Ruby', 'Ruby'), ('Rust', 'Rust'), ('Writing', 'Writing')], default='Javascript', max_length=30),
        ),
    ]
