# Generated by Django 2.1.2 on 2018-10-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0017_auto_20180928_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
