# Generated by Django 2.1.2 on 2018-10-19 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0018_problem_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='slug',
        ),
    ]
