# Generated by Django 2.1.2 on 2018-10-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0019_remove_problem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='language',
            field=models.CharField(choices=[('Psuedocode', 'Psuedocode'), ('C', 'C'), ('C++', 'C++'), ('Go', 'Go'), ('Java', 'Java'), ('Javascript', 'Javascript'), ('Python', 'Python'), ('Ruby', 'Ruby'), ('Rust', 'Rust'), ('Swift', 'Swift'), ('Writing', 'Writing')], default='Javascript', max_length=30),
        ),
    ]
